### ISSUE TITLE
Spring Cloud 全链路追踪实现 | 城南书客

### ISSUE THREAD

**Issue by ityard** [ityard/ityard.github.io#9]
https://ityard.github.io/spring%20cloud/2019/06/27/SpringCloudTrace/ 

 简介 在微服务架构下存在多个服务之间的相互调用，当某个请求变慢或不可用时，我们如何快速定位服务故障点呢？链路追踪的实现就是为了解决这一问题，本文采用Sleuth+Zipkin+RabbitMQ+ES+Kibana实现。

**Comment by 996i** [comment]
xjgvvh
